# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  ambevdeveloperevaluationwebapi:
    image: ambevdeveloperevaluationwebapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5119:5119
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
